### PR TITLE
*New* JS SDK async loading fix when using muse-components

### PR DESCRIPTION
**Pull request by nbierdeman**
Removed the DOMContentLoaded event listener in the setup() hook to eliminate the current race condition that had been resulting in the JS SDK failing to load async when using muse-components.

### CODE REVIEW

**Comment by nbierdeman** [comment]
@bluepnume @gregjopa How's this look?

**Review by gregjopa — APPROVED** [review]
Looks good to me!

**Review by bluepnume — APPROVED** [review]
LGTM!

**Comment by nbierdeman** [comment]
@gregjopa Do you have any ideas for getting the Travis CI build to pass? I've tried closing the PR and reopening it to kick off a new build, but unfortunately, it failed again.

**Comment by bluepnume** [comment]
Looking at the failed build -- one thing that would help is to change this line: https://github.com/paypal/paypal-muse-components/blob/master/.travis.yml#L3 to `  - "lts/*"`

**Comment by nbierdeman** [comment]
@bluepnume Ok, thanks! I'll give it a shot.

**Comment by gregjopa** [comment]
Here's a fix for the CI build which should unblock this PR: https://github.com/paypal/paypal-muse-components/pull/112

**Pull request merged**
